//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTUDQL2.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhatKiHeThong
    {
        public int id { get; set; }
        public string MaNV { get; set; }
        public string MayTinh { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public string TenChucNang { get; set; }
        public string HanhDong { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
