//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTUDQL2.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinToChucCaNhan
    {
        public string TenDonVi { get; set; }
        public string DiaCHi { get; set; }
        public string DTBan { get; set; }
        public string DTDD { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string LinhVuc { get; set; }
        public string MST { get; set; }
        public string GPKD { get; set; }
        public int Ma { get; set; }
    }
}
