//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.CHiTietBanHang = new HashSet<CHiTietBanHang>();
            this.ChiTietMuaHang = new HashSet<ChiTietMuaHang>();
        }
    
        public string MaHang { get; set; }
        public string TenHang { get; set; }
        public string MaDVT { get; set; }
        public string XuatXu { get; set; }
        public Nullable<int> Thue { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public Nullable<int> TonKhoToiThieu { get; set; }
        public Nullable<int> TonKhoHienTai { get; set; }
        public string MaNCC { get; set; }
        public Nullable<int> GiaMua { get; set; }
        public Nullable<int> GiaBanSi { get; set; }
        public Nullable<int> GiaBanLe { get; set; }
        public string MaKhoHang { get; set; }
        public string MaNhomHang { get; set; }
        public string MaSKU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHiTietBanHang> CHiTietBanHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuaHang> ChiTietMuaHang { get; set; }
        public virtual DonViTinh DonViTinh { get; set; }
        public virtual KhoHang KhoHang { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
        public virtual NhomHangHoa NhomHangHoa { get; set; }
    }
}
