//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuaHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MuaHang()
        {
            this.ChiTietMuaHang = new HashSet<ChiTietMuaHang>();
        }
    
        public string MaPhieuMuaHang { get; set; }
        public string MaNPP { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<int> MaLoaiTien { get; set; }
        public string DieuKhoanThanhToan { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public string TongTien { get; set; }
        public string MaNV { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string SoHoaDonVAT { get; set; }
        public string SoPhieuVietTay { get; set; }
        public string MaNhapKho { get; set; }
        public string HinhThucThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietMuaHang> ChiTietMuaHang { get; set; }
        public virtual KhoHang KhoHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhaPhanPhoi NhaPhanPhoi { get; set; }
    }
}
