//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.DTO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanHangEntities : DbContext
    {
        public QLBanHangEntities()
            : base("name=QLBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BanHang> BanHang { get; set; }
        public virtual DbSet<BoPhan> BoPhan { get; set; }
        public virtual DbSet<CHiTietBanHang> CHiTietBanHang { get; set; }
        public virtual DbSet<ChiTietMuaHang> ChiTietMuaHang { get; set; }
        public virtual DbSet<DonViTinh> DonViTinh { get; set; }
        public virtual DbSet<HangHoa> HangHoa { get; set; }
        public virtual DbSet<KhachHang> KhachHang { get; set; }
        public virtual DbSet<KhoHang> KhoHang { get; set; }
        public virtual DbSet<KhuVuc> KhuVuc { get; set; }
        public virtual DbSet<LoaiKH> LoaiKH { get; set; }
        public virtual DbSet<LoaiTien> LoaiTien { get; set; }
        public virtual DbSet<Mua_BanTam> Mua_BanTam { get; set; }
        public virtual DbSet<MuaHang> MuaHang { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<NhaPhanPhoi> NhaPhanPhoi { get; set; }
        public virtual DbSet<NhatKiHeThong> NhatKiHeThong { get; set; }
        public virtual DbSet<NhomHangHoa> NhomHangHoa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoanNguoiDung> TaiKhoanNguoiDung { get; set; }
        public virtual DbSet<ThongTinToChucCaNhan> ThongTinToChucCaNhan { get; set; }
        public virtual DbSet<ThuTien> ThuTien { get; set; }
        public virtual DbSet<V_ThongTinLogin> V_ThongTinLogin { get; set; }
    }
}
