//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuTien
    {
        public string MaPhieuThu { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public string DuNo { get; set; }
        public string MaKH { get; set; }
        public string SoTienTra { get; set; }
        public string MaBanHang { get; set; }
        public Nullable<int> idLoaiTien { get; set; }
    
        public virtual BanHang BanHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual LoaiTien LoaiTien { get; set; }
    }
}
