//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BUS.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ThongTinLogin
    {
        public string TenTaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string TenNV { get; set; }
        public string ChucVu { get; set; }
        public string MaNV { get; set; }
        public int id { get; set; }
        public string MaBP { get; set; }
    }
}
