//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTUDQL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanHang()
        {
            this.CHiTietBanHangs = new HashSet<CHiTietBanHang>();
            this.ThuTiens = new HashSet<ThuTien>();
        }
    
        public string MaPhieuBanHang { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string NoCu { get; set; }
        public string NoMoi { get; set; }
        public string DieuKhoanThanhToan { get; set; }
        public Nullable<System.DateTime> HanThanhToan { get; set; }
        public string MaNVBan { get; set; }
        public string TongTien { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHiTietBanHang> CHiTietBanHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuTien> ThuTiens { get; set; }
    }
}
