using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using BUS.DTO;

namespace DoAn_LTUDQL2
{
    public partial class frm_KhuVuc : DevExpress.XtraEditors.XtraForm
    {
        QLBanHangEntities dbContext = new QLBanHangEntities();
        public frm_KhuVuc()
        {
            InitializeComponent();
          
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.KhuVuc.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    khuVucsBindingSource.DataSource = dbContext.KhuVuc.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            frm_ThemKV kv = new frm_ThemKV(); kv.Show();
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            frm_SuaKV kv = new frm_SuaKV(); kv.Show();
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            frm_XoaKV kv = new frm_XoaKV(); kv.Show();
        }
        public void load()
        {
            gridControl1.RefreshDataSource();
            List<KhuVuc> kv = new List<KhuVuc>();
            kv = dbContext.KhuVuc.ToList();

            gridControl1.DataSource = kv;
        }
        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            load();
        }
    }
}