using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace DoAn_LTUDQL2
{
    public partial class frm_KhuVuc : DevExpress.XtraEditors.XtraForm
    {
        DoAn_LTUDQL2.QLBanHangEntities dbContext = new DoAn_LTUDQL2.QLBanHangEntities();
        public frm_KhuVuc()
        {
            InitializeComponent();
          
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.KhuVucs.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    khuVucsBindingSource.DataSource = dbContext.KhuVucs.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
            dbContext.SaveChanges();
        }
    }
}