using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace DoAn_LTUDQL2
{
    public partial class frm_NhaPhanPhoi : DevExpress.XtraEditors.XtraForm
    {
        public frm_NhaPhanPhoi()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            BUS.DTO.QLBanHangEntities dbContext = new BUS.DTO.QLBanHangEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.NhaPhanPhoi.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                nhaPhanPhoiBindingSource.DataSource = dbContext.NhaPhanPhoi.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void frm_NhaPhanPhoi_Load(object sender, EventArgs e)
        {

        }

        private void button1_Click(object sender, EventArgs e)
        {
            frm_ThemNPP npp = new frm_ThemNPP(); npp.Show();
        }

        private void button2_Click(object sender, EventArgs e)
        {
            frm_SuaNPP frm = new frm_SuaNPP(); frm.Show();
        }

        private void button3_Click(object sender, EventArgs e)
        {
            frm_XoaNPP frm = new frm_XoaNPP(); frm.Show();
        }
    }
}