using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;
using BUS.DTO;
using BUS.DAO;

namespace DoAn_LTUDQL2
{
    public partial class frm_BoPhan : DevExpress.XtraEditors.XtraForm
    {
        static QLBanHangEntities dbContext = new QLBanHangEntities();
        public frm_BoPhan()
        {
            InitializeComponent();        
        }

        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            frm_ThemBoPhan frmbophan = new frm_ThemBoPhan();
            frmbophan.ShowDialog();
        }

        private void frm_BoPhan_Load(object sender, EventArgs e)
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            QLBanHangEntities dbContext = new QLBanHangEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.BoPhan.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.BoPhan.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void barButtonItem3_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            DialogResult dialogResult = MessageBox.Show("Bạn muốn xóa dòng này không ", "Cảnh báo", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (dialogResult == DialogResult.Yes)
            {
                string pName = gridView1.GetFocusedRowCellValue("MaNV").ToString();
                var bp = (from item in dbContext.BoPhan where item.MaBo == pName select item).FirstOrDefault();
                dbContext.BoPhan.Remove(bp);
                dbContext.SaveChanges();
                MessageBox.Show("Xóa Thành Công");
                frm_BoPhan_Load(sender, e);
            }
            else if (dialogResult == DialogResult.No)
            {
                return;
            }
        }

        private void barButtonItem4_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            frm_BoPhan_Load(sender, e);
        }

        private void barButtonItem6_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            this.Close();
        }

        private void barButtonItem2_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            string ma = gridView1.GetFocusedRowCellValue("MaBo").ToString();
            nvStatic = BoPhanDAO.get(ma);
            frm_SuaBoPhan frm = new frm_SuaBoPhan();
            frm.SuaBoPhan += Frm_SuaBoPhan;
            frm.ShowDialog();
        }

        private void Frm_SuaBoPhan(BoPhan nv)
        {
            if (BoPhanDAO.sua(nv) > 0)
            {
                XtraMessageBox.Show("Sửa thành công");
            }
        }
        public static BoPhan nvStatic = null;
        private void gridView1_RowClick(object sender, DevExpress.XtraGrid.Views.Grid.RowClickEventArgs e)
        {
            string ma = gridView1.GetRowCellValue(e.RowHandle, "MaBo").ToString();
            nvStatic = BoPhanDAO.get(ma);
        }
    }
    
    
}