//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LTUDQL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.BanHangs = new HashSet<BanHang>();
            this.NhatKiHeThongs = new HashSet<NhatKiHeThong>();
            this.ThuTiens = new HashSet<ThuTien>();
        }
    
        public string MaKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<int> LoaiKH { get; set; }
        public string MaKhuVuc { get; set; }
        public string DiaChi { get; set; }
        public string MST { get; set; }
        public string DTBan { get; set; }
        public string DTDD { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string STK { get; set; }
        public string NganHang { get; set; }
        public string GioiHanNo { get; set; }
        public string NoHienTai { get; set; }
        public Nullable<int> ChietKhau { get; set; }
        public string NguoiLienHe { get; set; }
        public string NickYM { get; set; }
        public string NickSkype { get; set; }
        public Nullable<int> TinhTrangQuanLy { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BanHang> BanHangs { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
        public virtual LoaiKH LoaiKH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhatKiHeThong> NhatKiHeThongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuTien> ThuTiens { get; set; }
    }
}
