using BUS.DTO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BUS.DAO
{
    public static class BanHangDAO
    {
        static QLBanHangEntities dbContext = new QLBanHangEntities();
        public static BindingList<Mua_BanTam> LoadDS()
        {
            // Instantiate a new DBContext

            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Mua_BanTam.Load();
            // This line of code is generated by Data Source Configuration Wizard
            return dbContext.Mua_BanTam.Local.ToBindingList();
        }
        public static int LayMaPhieuBanHang()
        {
            return (from item in dbContext.BanHang orderby item.NgayBan descending select item.MaPhieuBanHang).FirstOrDefault();
        }
    }
}
