using BUS.DTO;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BUS.DAO
{
    class MuaHangDAO
    {
        static QLBanHangEntities dbContext = new QLBanHangEntities();
        public static BindingList<Mua_BanTam> LoadDS()
        {
            // Instantiate a new DBContext
            
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.Mua_BanTam.Load();
            // This line of code is generated by Data Source Configuration Wizard
            return dbContext.Mua_BanTam.Local.ToBindingList();
        }
        public static int LayMaPhieuMuaHang()
        {
            return  (from item in dbContext.MuaHang orderby item.NgayLap descending select item.MaPhieuMuaHang ).FirstOrDefault();
        }
        public static List< V_NhaPhanPhoi> LoadNhaPhanPhoi()
        {
            return (from item in dbContext.V_NhaPhanPhoi select item).ToList();
        }
        public static List<V_NhanVien> LoadNhanVien()
        {
          return  (from item in dbContext.V_NhanVien select item).ToList();
        }
        public static List<V_KhoHang> LoadKhoHang()
        {
            return (from item in dbContext.V_KhoHang select item).ToList();
        }
        public static List<V_HangHoa> LoadHangHoa()
        {
            return (from item in dbContext.V_HangHoa select item).ToList();
        }
    }
}
